<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="9" assertions="8" errors="4" warnings="0" failures="5" skipped="0" time="0.436577">
    <testsuite name="App" tests="9" assertions="8" errors="4" warnings="0" failures="5" skipped="0" time="0.436577">
      <testsuite name="Tests\Unit\AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" tests="9" assertions="8" errors="4" warnings="0" failures="5" skipped="0" time="0.436577">
        <testcase name="testModelCanInsertAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="25" assertions="1" time="0.090100">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\AuthorModelTest::testModelCanInsertAuthor
Failed asserting that false is of type "int".

C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:33
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</failure>
        </testcase>
        <testcase name="testModelCanFindAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="37" assertions="0" time="0.053878">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanFindAuthor
CodeIgniter\Database\Exceptions\DatabaseException: Table 'books_management_ci4_test.tests_autor' doesn't exist

C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:647
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Database\BaseBuilder.php:1616
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Model.php:203
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\BaseModel.php:580
C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:44
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</error>
        </testcase>
        <testcase name="testModelCanUpdateAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="50" assertions="0" time="0.045844">
          <error type="InvalidArgumentException">Tests\Unit\AuthorModelTest::testModelCanUpdateAuthor
InvalidArgumentException: update(): argument #1 ($id) should not be boolean.

C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\BaseModel.php:952
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Model.php:812
C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:61
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</error>
        </testcase>
        <testcase name="testModelCanDeleteAuthor" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="68" assertions="0" time="0.042848">
          <error type="InvalidArgumentException">Tests\Unit\AuthorModelTest::testModelCanDeleteAuthor
InvalidArgumentException: delete(): argument #1 ($id) should not be boolean.

C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\BaseModel.php:1100
C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:75
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</error>
        </testcase>
        <testcase name="testModelValidationFailsWithEmptyName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="81" assertions="2" time="0.062527">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithEmptyName
Failed asserting that an array has the key 'name'.

C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:91
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</failure>
        </testcase>
        <testcase name="testModelValidationFailsWithDuplicateName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="94" assertions="2" time="0.043480">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithDuplicateName
Failed asserting that an array has the key 'name'.

C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:105
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</failure>
        </testcase>
        <testcase name="testModelValidationFailsWithInvalidCharacters" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="108" assertions="2" time="0.042326">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\AuthorModelTest::testModelValidationFailsWithInvalidCharacters
Failed asserting that an array has the key 'name'.

C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:118
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</failure>
        </testcase>
        <testcase name="testModelValidationPassesWithValidName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="121" assertions="1" time="0.023958">
          <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\Unit\AuthorModelTest::testModelValidationPassesWithValidName
Failed asserting that false is of type "int".

C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:128
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</failure>
        </testcase>
        <testcase name="testModelCanOrderByName" class="Tests\Unit\AuthorModelTest" classname="Tests.Unit.AuthorModelTest" file="C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php" line="131" assertions="0" time="0.031614">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">Tests\Unit\AuthorModelTest::testModelCanOrderByName
CodeIgniter\Database\Exceptions\DatabaseException: Table 'books_management_ci4_test.tests_autor' doesn't exist

C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Database\BaseConnection.php:647
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Database\BaseBuilder.php:1616
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\Model.php:243
C:\laragon\www\ci-books\vendor\codeigniter4\framework\system\BaseModel.php:641
C:\laragon\www\ci-books\tests\unit\AuthorModelTest.php:136
phpvfscomposer://C:\laragon\www\ci-books\vendor\phpunit\phpunit\phpunit:106</error>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
